[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
meridian = "ERtAbZetHFVmFKyTzfJd9LdMGsqu5b2TWeWc65sikPaX"

[programs.devnet]
meridian = "ERtAbZetHFVmFKyTzfJd9LdMGsqu5b2TWeWc65sikPaX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/meridian"]

[scripts]
test = "pnpm --filter @meridian/tests exec vitest run"

[toolchain]
anchor_version = "0.31.1"
