#!/bin/bash
set -euo pipefail

# Regenerates app/src/lib/techIcons.ts by fetching each slug+color pair
# from cdn.simpleicons.org and inlining the SVG as a base64 data URL.
# Plus three hand-drawn monograms for brands NOT on simpleicons
# (phantom, anchor, pyth) — these are also pre-base64'd so the resulting
# module is fully static and contains zero runtime conversion logic.
#
# Why this exists: Safari's Strict tracking-prevention silently drops <img>
# requests to cdn.simpleicons.org (the same Cross-Origin-Resource-Policy
# quirk walletIcons.ts documents). Inlining removes that failure mode and
# also removes a deploy-day risk that the CDN goes down during a demo.
#
# Run from the repo root:   bash scripts/fetch-tech-icons.sh
# Commit the resulting diff.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/app/src/lib/techIcons.ts"
TMP="$(mktemp)"

declare -a ICONS=(
  "rust:c1763a"
  "nextdotjs:ffffff"
  "nodedotjs:339933"
  "solana:9945FF"
  "typescript:3178c6"
  "react:61dafb"
  "tailwindcss:06b6d4"
  "reactquery:ff4154"
  "pnpm:F69220"
  "vitest:729b1b"
  "render:46e3b7"
  "github:ffffff"
  "gitlab:fc6d26"
)

# Hand-drawn monograms for brands not on simpleicons. Each is a small SVG
# string; the script base64s these the same way it base64s the fetched ones,
# so every map entry in the generated file is a literal `data:` URL.
PHANTOM_SVG='<svg xmlns="http://www.w3.org/2000/svg" width="108" height="108" viewBox="0 0 108 108" fill="none"><rect width="108" height="108" rx="26" fill="#AB9FF2"/><path fill-rule="evenodd" clip-rule="evenodd" d="M46.5267 69.9229C42.0054 76.8509 34.4292 85.6182 24.348 85.6182C19.5824 85.6182 15 83.6563 15 75.1342C15 53.4305 44.6326 19.8327 72.1268 19.8327C87.768 19.8327 94 30.6846 94 43.0079C94 58.8258 83.7355 76.9122 73.5321 76.9122C70.2939 76.9122 68.7053 75.1342 68.7053 72.314C68.7053 71.5783 68.8275 70.7812 69.0719 69.9229C65.5893 75.8699 58.8685 81.3878 52.5754 81.3878C47.993 81.3878 45.6713 78.5063 45.6713 74.4598C45.6713 72.9884 45.9768 71.4556 46.5267 69.9229ZM83.6761 42.5794C83.6761 46.1704 81.5575 47.9658 79.1875 47.9658C76.7816 47.9658 74.6989 46.1704 74.6989 42.5794C74.6989 38.9885 76.7816 37.1931 79.1875 37.1931C81.5575 37.1931 83.6761 38.9885 83.6761 42.5794ZM70.2103 42.5795C70.2103 46.1704 68.0916 47.9658 65.7216 47.9658C63.3157 47.9658 61.233 46.1704 61.233 42.5795C61.233 38.9885 63.3157 37.1931 65.7216 37.1931C68.0916 37.1931 70.2103 38.9885 70.2103 42.5795Z" fill="#FFFDF8"/></svg>'
ANCHOR_SVG='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><rect width="24" height="24" rx="5" fill="#512BD4"/><path d="M12 4.5a1.6 1.6 0 0 0-1.6 1.6 1.6 1.6 0 0 0 1 1.49V9.5h-1.7v1.5h1.7v6.05a4.55 4.55 0 0 1-3.55-3.05h1.55l-2.4-3-2.4 3h1.55a6 6 0 0 0 5.85 4.55 6 6 0 0 0 5.85-4.55h1.55l-2.4-3-2.4 3h1.55a4.55 4.55 0 0 1-3.55 3.05V11h1.7V9.5h-1.7V7.59a1.6 1.6 0 0 0 1-1.49A1.6 1.6 0 0 0 12 4.5z" fill="#ffffff"/></svg>'
PYTH_SVG='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><rect width="24" height="24" rx="5" fill="#0a3d35"/><path d="M6 7v10M18 7v10M6 7h12" stroke="#4ec9b0" stroke-width="2.5" stroke-linecap="round"/></svg>'

declare -a MANUAL=(
  "phantom:AB9FF2:$PHANTOM_SVG"
  "anchor:512BD4:$ANCHOR_SVG"
  "pyth:4ec9b0:$PYTH_SVG"
)

cat > "$TMP" <<'HEADER'
// Inlined tech-stack logos used by /architecture. Generated by
// scripts/fetch-tech-icons.sh. DO NOT EDIT BY HAND — re-run the script and
// commit the result.
//
// Why inline: Safari's Strict tracking-prevention silently drops <img>
// requests to cdn.simpleicons.org (the Cross-Origin-Resource-Policy quirk
// walletIcons.ts already documents). Inlining the SVGs as data: URLs
// removes the cross-origin fetch entirely AND removes a deploy-day risk
// that the CDN could go down during a demo. Mermaid 10 accepts data: URLs
// in <img src="..."> nodes the same way it accepts regular URLs, so the
// topology diagram still renders identically.
//
// Each entry is a base64-encoded SVG. Simpleicons-sourced entries embed
// the requested fill color in the SVG itself; hand-drawn monograms
// (phantom, anchor, pyth) are written directly in the script because
// those brands are not on cdn.simpleicons.org. Regenerate by running:
//
//   bash scripts/fetch-tech-icons.sh
//
// then committing the diff.

/* eslint-disable max-len */

export interface TechIcon {
  readonly slug: string;
  readonly color: string;
  readonly dataUrl: string;
}

export const TECH_ICONS: Record<string, TechIcon> = {
HEADER

emit() {
  local slug="$1"
  local color="$2"
  local raw="$3"
  local b64
  b64=$(printf %s "$raw" | base64 | tr -d '\n')
  cat >> "$TMP" <<ENTRY
  "${slug}": {
    slug: "${slug}",
    color: "${color}",
    dataUrl: "data:image/svg+xml;base64,${b64}",
  },
ENTRY
}

for spec in "${ICONS[@]}"; do
  slug="${spec%%:*}"
  color="${spec##*:}"
  url="https://cdn.simpleicons.org/${slug}/${color}"
  echo "fetching ${slug} (${color})..." >&2
  raw=$(curl -fsSL "$url")
  if [[ -z "$raw" ]]; then
    echo "FAIL: empty body for ${slug}" >&2
    exit 1
  fi
  emit "$slug" "$color" "$raw"
done

for spec in "${MANUAL[@]}"; do
  IFS=':' read -r slug color svg <<<"$spec"
  echo "embedding hand-drawn ${slug}..." >&2
  emit "$slug" "$color" "$svg"
done

cat >> "$TMP" <<'FOOTER'
};

/**
 * Resolve a tech icon's data URL by simpleicons slug.
 * Throws if the slug was not pre-fetched — every architecture-page reference
 * MUST round-trip through this helper so a typo never silently falls back to
 * a CDN request (which would re-introduce the Safari failure mode).
 */
export function techIconUrl(slug: string): string {
  const entry = TECH_ICONS[slug];
  if (!entry) {
    throw new Error(
      `techIconUrl: no inlined icon for slug "${slug}". Add it to ` +
        `scripts/fetch-tech-icons.sh and re-run the script (or add a hand-drawn ` +
        `monogram to the MANUAL array in the same file). Loading from ` +
        `cdn.simpleicons.org at runtime is forbidden because Safari Strict ` +
        `tracking-prevention silently drops those requests.`,
    );
  }
  return entry.dataUrl;
}
FOOTER

mv "$TMP" "$OUT"
echo
echo "=== wrote $OUT ==="
wc -l "$OUT"
